name: Cypress Test

# runs afer each push to the cypressCI branch
on:
  push:
    branches: [ cypressCI ]

jobs:
  cypress-run:
      runs-on: ubuntu-22.04
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            ref: cypressCI
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - run: npm ci
        - name: Run Cypress tests
          run: npm run test:chrome
        - name: Copy test execution videos
          run: |
            mkdir public
            cp -r cypress/videos public/videos
        - name: Merge test results into one
          run: npm run report:merge
        - name: Generate HTML report
          run: npm run report:generate
        - name: Deploy
          uses: peaceiris/actions-gh-pages@v3
          if: github.ref == 'refs/heads/cypressCI'
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./public